General Reference (Physical Directory)/Message Boards (Web Application)/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.shortcuts import reverse

from accounts import views as account_views

app_name = 'accounts'

urlpatterns = [
    path('sign-up', account_views.userSignup, name='sign-up'),
    path('log-off', account_views.userLogoff, name='log-off'),
    path('log-in', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('my-account', account_views.UserUpdateView.as_view(), name='my-account')
]

General Reference (Physical Directory)/Message Boards (Web Application)/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    ##/
    path('',views.BoardListView.as_view(),name='index'),
    path('<str:board_name>/topics',views.TopicListView.as_view(), name='topics'),
    # path('<str:board_name>/topics',views.topics,name='topics'),
    path('<str:board_name>/topic/<int:topic_id>',views.PostListView.as_view(),name='view-topic'),
    path('<str:board_name>/create-topic',views.createTopic,name='create-topic'),
    path('<str:board_name>/create-topic/submit',views.createTopic,name='create-topic/submit'),
    path('<str:board_name>/topic/<int:topic_id>/create-post',views.createPost,name='create-post'),
    path('<str:board_name>/topic/<int:topic_id>/create-post/submit',views.createPost,name='create-post/submit'),
    path('<str:board_name>/topic/<int:topic_id>/edit-post/<int:post_id>',views.editPost,name='edit-post'),
    path('<str:board_name>/topic/<int:topic_id>/edit-post/<int:post_id>/submit',views.editPost, name='edit-post/submit'),
    path('contact-admin',views.contactAdmin,name='contact-admin')
]

def printUrlPatterns():
    for url in urlpatterns:
        print(str(url.callback.__name__).strip() + ","
              + '/' + str(url.pattern).strip() + ","
              + url.name)

General Reference (Physical Directory)/Message Boards (Web Application)/myproject/urls.py
from django.urls import path, include
from django.contrib import admin
import django.contrib.auth.views as auth_views

from accounts import views as account_views

app_name = 'myproject'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html',
             email_template_name='accounts/password_reset_email.html',
             subject_template_name='accounts/password_reset_subject.txt'
         ),
         name='password_reset'),
    path('reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z_\-]{1,13}-[0-9A-Za-z_\-]{1,20})',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('settings/password',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('settings/password/done', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done')
]

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/models.py
from django.db import models

# Create your models here.

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate

class UserSignupForm(UserCreationForm):
    email = forms.CharField(required=True, label='Email address', widget=forms.EmailInput)
    class Meta:
        model = User
        fields = ['username','email', 'password1', 'password2']

class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        fields = ['username','password']

    def clean(self):
        super().clean()

        username = self.cleaned_data.get('username')
        password = self.cleaned_data.get('password')
        user = authenticate(username=username,password=password)

        if user is None:
            self.add_error('username','Username/password combination does not match any record in our system')
            self.add_error('password','Username/password combination does not match any record in our system')

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/views.py
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404
from accounts.forms import UserSignupForm, UserLoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.views.generic.edit import UpdateView
from django.urls import reverse_lazy
from django.utils.decorators import method_decorator

# Create your views here.
def userSignup(request):
    form = UserSignupForm()

    if request.method == 'POST':
        form = UserSignupForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request,user)

            return HttpResponseRedirect(reverse('boards:index'))

    return render(request, 'accounts/sign-up.html',context={'form': form})

def userLogoff(request):
    if request.method == 'GET':
        logout(request)
        return HttpResponseRedirect(reverse('boards:index'))

def userLogin(request):
    form = UserLoginForm()
    if request.method == 'POST':
        form = UserLoginForm(request.POST)
        if form.is_valid():
            user = authenticate(request, username=form.cleaned_data['username'], password=form.cleaned_data['password'])
            print(user)
            if user is not None:
                login(request, user)
                return HttpResponseRedirect(reverse('boards:index'))

    return render(request, 'accounts/login.html',context={'form':form, 'next': request.GET['next']})

class UserUpdateView(UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email',)
    template_name = 'accounts/my-account.html'
    success_url = reverse_lazy('accounts:my-account')

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

    def get_object(self):
        return self.request.user

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/base.html
{% load static %}
<html>
{% include 'boards/head.html'%}
<body style="background-image:url('{% static 'images/topography.png' %}')">
	<div class="container" style="width:50rem">
		<div class="card mt-5">
			<div class="card-body">
				<h2 class="card-title text-center">{% block title %}{% endblock %}</h2>
				{% block content %}
                {% endblock %}
			</div>
		</div>
	</div>
</html>

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/login.html
{% extends 'accounts/base.html' %}
{% block title%}User Log-in{% endblock%}
{% block content %}
	{% if error_string %}
	<p>{{ error_string }}</p>
	{% endif %}
	<form method="post" action="{% url 'accounts:login' %}" novalidate>
		{% csrf_token %}
		<input type="hidden" name="next" value ="{{ next }}">
		{% include 'boards/form.html' %}
		<br><button class="btn btn-primary" type="submit"/>Submit</button>
	</form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/my-account.html
{% extends 'accounts/base.html' %}
{% block title%}Manage Account{% endblock%}
{% block content %}
	<form method="post" novalidate>
        {% csrf_token %}
        {% include 'boards/form.html' %}
        <button type="submit" class="mt-3 btn btn-primary">Save changes</button>
    </form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_change.html
{% extends 'accounts/base.html' %}
{% block title%}Change Password{% endblock%}
{% block content %}
    <form method="post" novalidate>
        {% csrf_token %}
        {% include 'boards/form.html'%}
        <button type="submit" class="mt-3 btn btn-primary">Change Password</button>
    </form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_change_done.html
{% extends 'accounts/base.html' %}
{% block title%}Success{% endblock%}
{% block content %}
	{% if error_string %}
	<p>{{ error_string }}</p>
	{% endif %}
	<form method="post" novalidate>
            {% csrf_token %}
            {% include 'boards/form.html'%}
            <div class="alert alert-success">
                <strong>Success!</strong> Your password has been changed.
            </div>
            <button href=""{% url 'boards:index' %}" type="submit" class="btn btn-primary">Return to home page</button>
        </form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_reset.html
{% extends 'accounts/base.html' %}
{% block title%}Reset your password{% endblock%}
{% block content %}
	{% if error_string %}
	<p>{{ error_string }}</p>
	{% endif %}
	<form method="post" novalidate>
        {% csrf_token %}
        {% include 'boards/form.html'%}
        <button type="submit" class="mt-3 btn btn-primary">Send password reset</button>
    </form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_reset_complete.html
{% extends 'accounts/base.html' %}
{% block title%}Password Reset{% endblock%}
{% block content %}
    <p>Your password has been set.  You may go ahead and log in now.</p>
    <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Log in</a>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_reset_confirm.html
{% extends 'accounts/base.html' %}
{% block title%}Password Reset Confirmation{% endblock%}
{% block content %}
	<form method="post" novalidate>
        {% csrf_token %}
        {% include 'boards/form.html'%}
       <button type="submit" class="btn btn-primary">Change my password</button>
    </form>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_reset_done.html
{% extends 'accounts/base.html' %}
{% block title%}Reset your password{% endblock%}
{% block content %}
    <p>Check your email for a link to reset your password. If it doesn't within a few minutes, check your spam folder.</p>
    <a href="{% url 'accounts:login' %}" class="btn btn-secondary btn-block">Return to login</a>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/password_reset_email.html
Hi there,

Someone asked for a password reset for the email address {{ email }}.
Follow the link below:
{{ protocol }}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

In case you forgot your Django Boards username: {{ user.username }}

If clicking the link above doesn't work, please copy and paste the URL
in a new browser window instead.

If you've received this mail in error, it's likely that another user entered
your email address by mistake while trying to reset a password. If you didn't
initiate the request, you don't need to take any further action and can safely
disregard this email.

Thanks,

The Django Boards Team

General Reference (Physical Directory)/Message Boards (Web Application)/accounts/templates/accounts/sign-up.html
{% extends 'accounts/base.html' %}
{% block title%}Sign Up{% endblock%}
{% block content %}
<form method="post" action="{% url 'accounts:sign-up'%}" novalidate>
	<form method="post" action="{% url 'accounts:sign-up'%}" novalidate>
		{% csrf_token %}
		{% include 'boards/form.html' %}
		<br><button type="submit" class="btn btn-primary">Create an account</button>
	</form>
</form>
{% endblock %}