General Reference (Physical Directory)/Message Boards (Web Application)/accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from django.shortcuts import reverse

from accounts import views as account_views

app_name = 'accounts'

urlpatterns = [
    path('sign-up', account_views.userSignup, name='sign-up'),
    path('log-off', account_views.userLogoff, name='log-off'),
    path('log-in', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('my-account', account_views.UserUpdateView.as_view(), name='my-account')
]

General Reference (Physical Directory)/Message Boards (Web Application)/boards/urls.py
from django.urls import path
from . import views

app_name = 'boards'

urlpatterns = [
    ##/
    path('',views.BoardListView.as_view(),name='index'),
    path('<str:board_name>/topics',views.TopicListView.as_view(), name='topics'),
    # path('<str:board_name>/topics',views.topics,name='topics'),
    path('<str:board_name>/topic/<int:topic_id>',views.PostListView.as_view(),name='view-topic'),
    path('<str:board_name>/create-topic',views.createTopic,name='create-topic'),
    path('<str:board_name>/create-topic/submit',views.createTopic,name='create-topic/submit'),
    path('<str:board_name>/topic/<int:topic_id>/create-post',views.createPost,name='create-post'),
    path('<str:board_name>/topic/<int:topic_id>/create-post/submit',views.createPost,name='create-post/submit'),
    path('<str:board_name>/topic/<int:topic_id>/edit-post/<int:post_id>',views.editPost,name='edit-post'),
    path('<str:board_name>/topic/<int:topic_id>/edit-post/<int:post_id>/submit',views.editPost, name='edit-post/submit'),
    path('contact-admin',views.contactAdmin,name='contact-admin')
]

def printUrlPatterns():
    for url in urlpatterns:
        print(str(url.callback.__name__).strip() + ","
              + '/' + str(url.pattern).strip() + ","
              + url.name)

General Reference (Physical Directory)/Message Boards (Web Application)/myproject/urls.py
from django.urls import path, include
from django.contrib import admin
import django.contrib.auth.views as auth_views

from accounts import views as account_views

app_name = 'myproject'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('boards/', include('boards.urls')),
    path('reset/',
         auth_views.PasswordResetView.as_view(
             template_name='accounts/password_reset.html',
             email_template_name='accounts/password_reset_email.html',
             subject_template_name='accounts/password_reset_subject.txt'
         ),
         name='password_reset'),
    path('reset/done',
         auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/(<uidb64>[0-9A-Za-z_\-]+)/(<token>[0-9A-Za-z_\-]{1,13}-[0-9A-Za-z_\-]{1,20})',
         auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/complete',
         auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'),
         name='password_reset_complete'),
    path('settings/password',
         auth_views.PasswordChangeView.as_view(template_name='accounts/password_change.html'), name='password_change'),
    path('settings/password/done', auth_views.PasswordChangeDoneView.as_view(template_name='accounts/password_change_done.html'), name='password_change_done')
]

General Reference (Physical Directory)/Message Boards (Web Application)/boards/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=200)

    def get_name_url_formatted(self):
        return self.name.replace(' ', '-').lower()

    def get_name_from_url_format(url_formatted_name):
        return url_formatted_name.replace('-',' ').title()

    def get_latest_post(self):
        return Post.objects.filter(topic__board=self).order_by('-created_at').first()

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    name_url_formatted = property(get_name_url_formatted)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=50)
    board = models.ForeignKey(Board,null=False,on_delete=models.PROTECT,related_name='topics')
    created_by = models.ForeignKey(User,null=False, on_delete=models.PROTECT, related_name='topics_created')
    updated_by = models.ForeignKey(User,null=False, on_delete=models.PROTECT, related_name='topics_updated')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now_add=True) #TODO: Should this *only* update when a user makes a post?
    views = models.PositiveIntegerField(default=0)

    def get_count_replies(self):
        if (Post.objects.filter(topic=self).count() - 1) < 0:
            return 0
        else:
            return Post.objects.filter(topic=self).count() - 1

    def get_last_post_user(self):
        if len(Post.objects.filter(topic=self)) == 0:
            return ''
        else:
            return Post.objects.filter(topic=self).order_by('-updated_by')[0].created_by.username

    def __str__(self):
        return self.subject

class Post(models.Model):
    subject = models.CharField(max_length=50)
    message = models.CharField(max_length=1000)
    topic = models.ForeignKey(Topic,null=False,on_delete=models.PROTECT,related_name='topics')
    created_by = models.ForeignKey(User, null=False,on_delete=models.PROTECT, related_name='posts_created')
    updated_by = models.ForeignKey(User, null=False, on_delete=models.PROTECT, related_name='posts_updated')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    in_reply_to = models.ForeignKey('self',null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.subject

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

General Reference (Physical Directory)/Message Boards (Web Application)/boards/forms.py
from django import forms
from boards.models import Topic, Post
from django.contrib.auth.models import User
from django.contrib.auth import authenticate
from django.contrib.auth.forms import AuthenticationForm
from django.core.validators import RegexValidator


class CreateTopicForm(forms.ModelForm):
    message = forms.CharField(label='Message'
                              , widget=forms.Textarea
                              , max_length=1000
                              )

    class Meta:
        model = Topic
        fields = ['subject','message']

class CreatePostForm(forms.ModelForm):
    in_reply_to_id = forms.IntegerField(widget=forms.HiddenInput,required=False)
    message = forms.CharField(widget=forms.Textarea, max_length = 1000)

    class Meta:
        model = Post
        fields = ['subject','message','in_reply_to_id']

class EditPostForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea, max_length=1000)

    class Meta:
        model = Post
        fields = ['subject','message']

General Reference (Physical Directory)/Message Boards (Web Application)/boards/views.py
from django.http import HttpResponse, HttpResponseBadRequest, HttpResponseForbidden
from django.shortcuts import render, HttpResponseRedirect, reverse, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.utils.timezone import now


from boards.models import *
from boards.forms import \
    CreateTopicForm, \
    CreatePostForm, \
    EditPostForm

from boards.view_helpers import *
from boards import view_helpers

class BoardListView(ListView):
    model=Board
    context_object_name='boards'
    template_name='boards/boards.html'


class TopicListView(ListView):
    model = Topic
    context_object_name = 'topics'
    template_name = 'boards/topics.html'
    paginate_by = 20

    def get_context_data(self, **kwargs):
        kwargs['board_name_url_formatted'] = self.board.name_url_formatted
        kwargs['board_name'] = self.board.name
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(Board,name=Board.get_name_from_url_format(self.kwargs['board_name']))
        queryset = Topic.objects.filter(board=self.board).order_by('-updated_at')
        return queryset

def topics(request, board_name):
    board = get_object_or_404(Board, name=Board.get_name_from_url_format(board_name))
    topics_queryset = view_helpers.getTopicsByBoard(board.id)
    page = request.GET.get('page',1)
    paginator = Paginator(topics_queryset, 10)

    #TODO: Provide descending order to topics on individual page

    topics = paginator.get_page(page)

    context = {
        'topics': topics
        , 'board_name_url_formatted': board.name_url_formatted
        , 'board_name': board.name
    }

    return render(request, 'boards/topics.html', context=context)

#TODO: Delete old view functions that have been replaced by GCBV
class PostListView(ListView):
    model = Post
    context_object_name = 'posts'
    template_name = 'boards/view-topic.html'
    paginate_by = 5

    def get_context_data(self, **kwargs):
        kwargs['current_user'] = self.request.user.username
        kwargs['topic'] = self.topic
        kwargs['board'] = self.topic.board
        kwargs['post_original'] = self.post_original
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        #TODO: Research: does this always execute before get_context_data?
        board_name = self.kwargs['board_name']
        topic_id = self.kwargs['topic_id']
        self.topic = get_object_or_404(Topic,board__name=Board.get_name_from_url_format(board_name), id=topic_id)
        self.topic.views += 1
        self.topic.save()
        queryset = Post.objects.filter(topic=self.topic).order_by('updated_at')
        self.post_original = view_helpers.safe_list_get(queryset,0)
        print(queryset)
        return queryset

def viewTopic(request, topic_id, board_name):
    topic = get_object_or_404(Topic, board__name=Board.get_name_from_url_format(board_name),id=topic_id)
    topic.views += 1
    topic.save()
    context = {
        'current_user':request.user.username,
        'topic': topic,
        'board': topic.board
    }

    return render(request, 'boards/view-topic.html', context=context)


@login_required
def createTopic(request, board_name):
    board = get_object_or_404(Board, name=Board.get_name_from_url_format(board_name))

    form = CreateTopicForm()

    if request.method == 'POST':
        form = CreateTopicForm(request.POST)
        if form.is_valid():
            created_topic = Topic.objects.create(
                board=board,
                subject=form.cleaned_data.get('subject'),
                created_by_id=request.user.id,
                updated_by_id=request.user.id
            )

            Post.objects.create(
                created_by_id=request.user.id,
                updated_by_id=request.user.id,
                topic=created_topic,
                subject=form.cleaned_data.get('subject'),
                message=form.cleaned_data.get('message')
            )
            return HttpResponseRedirect(reverse('boards:topics', kwargs={'board_name': board.name_url_formatted}))


    context = {
        'current_username': request.user.username,
        'board_name': board.name,
        'board_name_url_formatted':board.name_url_formatted,
        'form': form
    }

    return render(request,'boards/create-topic.html', context=context)

@login_required
def createPost(request, board_name, topic_id):
    board_name = board_name.replace('-', ' ')
    topic = get_object_or_404(Topic, board__name=Board.get_name_from_url_format(board_name),id=topic_id)
    recent_posts = Post.objects.filter(topic=topic).order_by('-created_at')[0:4]

    in_reply_to_post = view_helpers.getPost(view_helpers.getQueryDictItem(request, 'post_id'))
    if in_reply_to_post is not None:
        form = CreatePostForm(initial={'in_reply_to_id':in_reply_to_post.id})
    else:
        form = CreatePostForm()

    if request.method=='GET':
        context = {
            'board_name': board_name,
            'board_name_url_formatted': board_name,
            'topic': topic,
            'form': form,
            'recent_posts': recent_posts
        }

        return render(request, 'boards/create-post.html', context=context)


    if request.method == 'POST':
        form = CreatePostForm(request.POST)
        if form.is_valid():
            current_topic_posts = [post.id for post in Post.objects.filter(topic__id=topic_id)]

            if in_reply_to_post is not None \
                    and in_reply_to_post.id not in current_topic_posts:
                return HttpResponse('Not Acceptable', status=406)

            post = form.save(commit=False)
            post.created_by = request.user
            post.updated_by = request.user
            post.topic = topic
            post.topic.updated_at = now()
            topic.save()
            post.save()

            return HttpResponseRedirect(
                reverse('boards:view-topic', kwargs={'topic_id': topic_id, 'board_name': board_name}))
        else:
            context = {
                'board_name': board_name,
                'board_name_url_formatted': board_name,
                'topic': topic,
                'form': form,
                'recent_posts': recent_posts
            }
            return render(request, 'boards/create-post.html', context=context)

def editPost(request, board_name, topic_id, post_id):
    topic = get_object_or_404(Topic, id=topic_id)
    board = get_object_or_404(Board, name=Board.get_name_from_url_format(board_name))
    post = get_object_or_404(Post, id=post_id)
    in_reply_to_post = None if post.in_reply_to is None else Post.objects.get(id=post.in_reply_to.id)

    post_topic = post.topic
    post_board = post_topic.board

    form = EditPostForm(initial={'subject':post.subject, 'message':post.message})

    if request.user.is_anonymous:
        return HttpResponseRedirect(reverse('accounts:login'))

    if board != post_board or topic != post_topic:
        return HttpResponseBadRequest('Bad Request - post does not belong to topic or board provided')

    if post.created_by != request.user:
        return HttpResponseForbidden('User does not have permission to edit this post')

    if request.method == 'POST':
        form = EditPostForm(request.POST)

        if form.is_valid():
            post.subject = request.POST['subject']
            post.message = request.POST['message']
            post.save()
            return HttpResponseRedirect(
                reverse('boards:view-topic', kwargs={'board_name': board.name_url_formatted, 'topic_id': topic_id}))

    context = {
        'current_username': request.user.username,
        'board_name': board.name,
        'board_name_url_formatted': board.name_url_formatted,
        'topic': topic,
        'post': post,
        'in_reply_to_post_creator': in_reply_to_post.created_by.username if post.in_reply_to else None,
        'in_reply_to_post_subject': in_reply_to_post.subject if post.in_reply_to else None,
        'form': form
    }

    return render(request, 'boards/edit-post.html', context)

def contactAdmin(request):
    return render(request, 'boards/contact-site-admin.html')

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/base.html
<html>
    {% include 'boards/head.html'%}
    <body>
        {% include 'boards/header.html' %}
        <div class="pl-3 mt-3 container" id="content">
            {% block content %}{% endblock %}
            {% block footer %}
                {% include 'boards/footer.html' %}
            {% endblock %}
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
            <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>

            <script>
                var simplemde = new SimpleMDE();
            </script>
            <style>
                form label {
                    margin-top: 20px
                }

                .CodeMirror {
                    max-height:300px
                }

                table {
                    border:none
                }

                td {
                    border:none
                }

                th {
                    border:none
                }
            </style>
        </div>
    <body>
</html>

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/boards.html
{% extends 'boards/base.html' %}

{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page">Home</li>
  </ol>
</nav>
<div class="py-3">
	<p> Welcome to the Backpacking Forum. You may view or view or create posts in any of the Message Boards listed below.</p><p>Please post in accordance to the <a href=""> site rules <a/></p>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Board</th>
			<th>Topics</th>
			<th>Posts</th>
			<th>Latest Post</th>
		</tr>
	</thead>
	<tbody>
		{% for board in boards %}
		<tr>
			<td><a href="{% url 'boards:topics' board.name_url_formatted  %}">{{ board.name }}</a><br>{{ board.description }}</td>
			<td>{{ board.topics.count }}</td>
			<td>{{ board.get_posts_count }}</td>
			<td>{{ board.get_latest_post.created_by }} at {{ board.get_latest_post.created_at|date:"g:i a" }} on {{ board.get_latest_post.created_at|date:"D. m/d/y" }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/create-post.html
<!--
Mock-up at:

C:\Users\Ben\Documents\Side Projects\Project Workspace Root\Current\Django Progamming Tutorial (Internal) (2020-09-06)\Resources\UI Mock-ups\Create Post.drawio
-->

{% extends 'boards/base.html' %}
{% load static %}
{% load gravatar_tags %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'boards:index' %}">Home</a></li>
	  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'boards:topics' topic.board.name_url_formatted %}">{{ topic.board.name }}</a></li>
	  <li class="breadcrumb-item" aria-current="page">{{ topic.subject }}</li>
  </ol>
</nav>
<form style="margin-bottom:50px" method="post" action="{% url 'boards:create-post/submit' board_name_url_formatted topic.id %}" novalidate>
	{% csrf_token %}
	{% include 'boards/form.html' %}
	<button class="btn btn-primary my-2" type="submit">Create Post</button>
</form>
<h5>Recent Topic Posts</h5>
{% for post in recent_posts %}
<div class="card" style="margin-bottom:20px">
	<div class="card-body">
	  <div class="post-meta d-flex">
		  <div class="profile-image-container mr-auto" style="display:inline-block">
			  <img class="profile-image" style="height:100px" src='{{ post.created_by|gravatar }}'>
			  <p class="image-caption text-center">{{ post.created_by }}</p>
		  </div>
		  <div class="post-dates">
			  {{ post.created_at|date:"D. m/d/Y" }} at {{ post.created_at|date:"g:i a" }}
		  </div>
	  </div>
	  <div class="card-text">
		  <div class="my-4 p-2">{{ post.get_message_as_markdown }}</div>
	  </div>
  </div>
</div>
{% endfor %}
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/footer.html
<p style="margin: 20px 0px 20px 0px">Any questions or comments about the forum? You may contact a Site Administrator <a href="{% url 'boards:contact-admin' %}">here</a></p>

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/header.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand" href="{% url 'boards:index' %}">Backpacking Forum</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto">
        {% if user.is_authenticated %}
        <li class="nav-item dropdown active">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Signed in as <strong>{{ user.username }}</strong>
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-item" href="{% url 'accounts:my-account' %}">My Account</a>
            <a class="dropdown-item" href="{% url 'password_reset' %}">Change Password</a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-item" href="{% url 'accounts:log-off'%}">Sign-out</a>
          </div>
        </li>
        {% else %}
        <a class="btn btn-primary mr-2" href="{% url 'accounts:login'%}" role="button">Log-in</a>
        <a class="btn btn-primary" href="{% url 'accounts:sign-up'%}" role="button">Sign-up</a>
        {% endif %}
      </ul>
    </div>
  </div>
</nav>

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/topics.html
{% extends 'boards/base.html' %}
{% load humanize %}

{% block remaining_title %}{{ board_name|title }}{% endblock %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'boards:index' %}">Home</a></li>
	  <li class="breadcrumb-item" aria-current="page">{{ board_name }}</li>
  </ol>
</nav>
<p>You may either view a post below </p>
<form action="{% url 'boards:create-topic' board_name_url_formatted %}"><button class="btn btn-primary" type="submit">Create New Topic</button></form>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Topic</th>
			<th>Started By</th>
			<th>Replies</th>
			<th>Views</th>
			<th>Last Post</th>
		</tr>
	</thead>
	<tbody>
		{% for topic in page_obj %}
		<tr>
			<td><a href="{% url 'boards:view-topic' board_name_url_formatted topic.id %}">{{ topic.subject }}</a></td>
			<td>{{ topic.created_by }}</td>
			<td>{{ topic.get_count_replies }}</td>
			<td>{{ topic.views }}</td>
<!--			#TODO: The last post date displayed doesn't seem accurate - troubleshoot -->
			<td>{{ topic.get_last_post_user }}, {{ topic.updated_at|naturaltime }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if page_obj.has_other_pages %}
{% include 'boards/pagination.html' with object_type='Topics' %}
{% endif %}
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/user-login-mgmt.html
{% if user.is_authenticated %}
<ul>
    <li>You are currently logged-in as <strong>{{ user.username }}</strong></a></li>
    <li>Click <a href="{% url 'accounts:log-off'%}">here</a> to sign-out</a></li>
</ul>
{% else %}
<ul>
    <li><a href="{% url 'accounts:login' %}">User Login</a></li>
    <li><a href="{% url 'boards:sign-up' %}">User Sign-up</a></li>
</ul>
{% endif %}

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/view-topic-dev.html
{% extends 'boards/base.html '%}
{% block remaining_title%}
	<u><a href="{% url 'boards:topics' topic.board.name_url_formatted %}">{{ topic.board.name }}</a></u> > {{ topic.subject }}
{% endblock %}
{% block content %}
<form method="get"
	  class="mt-4"
	  action="{% url 'boards:create-post' topic.board.name_url_formatted topic.id %}">
	<input type="hidden" name="post_id" value="">
	<input type="submit" value="Reply">
</form>
{% for post in posts %}
<div class="user-post">
	<div class="user-post-inner" style="position:relative">
		<div class="user-post-meta" style="display:inline-block">
			<p>User: {{ post.created_by }} at {{ post.created_at}}
			<br>Subject: {{ post.subject }}</p>
		</div>
		<div class="user-post-controls" style="display:inline-block; position: absolute; top:0px; right:0px">
			<form method="get" action="{% url 'boards:edit-post' topic.board.name_url_formatted topic.id post.id %}" style="display:inline-block">
				<input type="submit" value="Edit">
			</form>
			<form method="get" action="{% url 'boards:create-post' topic.board.name_url_formatted topic.id %}" style="display:inline-block">
				<input type="submit" value="Reply">
				<input type="hidden" name="post_id" value="{{ post.id }}">
			</form>
		</div>
		<p>
			{{ post.message }}
		</p>
	</div>
</div>
{% endfor %}
{% endblock %}

General Reference (Physical Directory)/Message Boards (Web Application)/boards/templates/boards/view-topic.html
<!--
Resources: Implement Mock-up at "C:\Users\Ben\Documents\Side Projects\Project Workspace Root\Current\Django Progamming Tutorial (Internal) (2020-09-06)\Resources\UI Mock-ups\View Topic.drawio"

-->
{% extends 'boards/base.html '%}
{% load static %}
{% load humanize %}
{% load gravatar_tags %}
{% block content %}
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
	  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'boards:index' %}">Home</a></li>
	  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'boards:topics' board.name_url_formatted %}">{{ board.name }}</a></li>
	  <li class="breadcrumb-item" aria-current="page">{{ topic.subject }}</li>
  </ol>
</nav>
<form method="get"
	  class="mt-4 mb-4"
	  action="{% url 'boards:create-post' topic.board.name_url_formatted topic.id %}">
	<input type="hidden" name="post_id" value="">
	<button type="submit" class="btn btn-primary">Create New Post</button>
</form>
<div>
	{% for post in posts %}
	{% if post_original.id == post.id %}
	<div class="card" style="margin-bottom:50px">
	{% else %}
	<div class="card" style="margin-bottom:20px">
	{% endif %}
		{% if post_original.id == post.id %}
		<div class="card-header">
			{{ topic.subject }}
		</div>
		{% endif %}
		<div class="card-body">
		  <div class="post-meta d-flex">
		<!--
		#TODO: Document the below

		Described here: the mechanics of element positioning within this div.

		The (abbreviated) layout of this div is as such:

		post-meta
		  profile-image-container (inline-block)
			profile-image (inline-block)
			profile-image-caption (block)
		  post-dates

		 Although an inline-block style isn't explicitly set here on the 'profile-image-container', flex display (enabled in the parent div's class) seems to apply inline-block style to the child elements, as the default. 'profile-image-container' is necessary to center its contained 'profile-image-caption'. An inline-block element will only be as wide as its widest child. For that reason, we can position 'profile-image-caption' within the center of the 'profile-image-container', in the case that the 'profile-image' is the widest of the two element.And, because the profile-image-caption is a block element; it's knocked to the line below 'profile-image' (saving us from having to apply a <br> tag).

		Applying mr-auto to profile-image-container tells the browser to use whatever width is available for the remainder of the line for the parent container (including consideration of the other sibling divs of profile-image-container.
		-->
			  <div class="profile-image-container mr-auto" style="display:inline-block">
				  <img class="profile-image" style="height:100px" src='{{ post.created_by|gravatar }}'>
				  <p class="image-caption text-center">{{ post.created_by.username }}</p>
			  </div>
			  <div class="post-dates">
				  {{ post.created_at|naturaltime }}
			  </div>
		  </div>
		  <div class="card-text">
			  <div class="my-4 p-2">{{ post.get_message_as_markdown }} </div>
			  <form method="get" action="{% url 'boards:create-post' topic.board.name_url_formatted topic.id %}" style="display:inline-block">
					<button type="submit" class="btn btn-primary">Reply</button>
					<input type="hidden" name="post_id" value="{{ post.id }}">
				</form>
			  {% if current_user == post.created_by %}
			  <form method="get" action="{% url 'boards:edit-post' topic.board.name_url_formatted topic.id post.id %}" style="display:inline-block">
				  <button type="submit" class="btn btn-primary">Edit</button>
				</form>
			  {% endif %}
		  </div>
	  </div>
	</div>
	{% endfor %}
</div>
{% include 'boards/pagination.html' with object_type='Posts' %}
{% endblock %}